export { default as Navbar } from './Navbar'
export { default as Landing } from './Landing'
export { default as Hero } from './Hero'
export { default as InputBar } from './InputBar'
export { default as About } from './About'
export { default as GIS } from './GIS'
export { default as Files } from './Files'
export { default as Authors } from './Authors'
